---
development:
  cloud_name: mybandsource
  api_key: '882353443212822'
  api_secret: M1SrLJBWrBIkn8OLpmMIKKxsUJw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: mybandsource
  api_key: '882353443212822'
  api_secret: M1SrLJBWrBIkn8OLpmMIKKxsUJw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: mybandsource
  api_key: '882353443212822'
  api_secret: M1SrLJBWrBIkn8OLpmMIKKxsUJw
  enhance_image_tag: true
  static_image_support: false
